### ISSUE TITLE
No CUDA GPUs Error when running all 5 clients.

### ISSUE THREAD

**Issue by fahnub** [MenguChen/Federated_object_detection#6]
Works fine on two clients but when I run with 5 client I get this error

Namespace(config_file='data/task_configs/yolo/street_5/yolo_task1.json', gpu=1, ignore_load='True', port=1234)
client run on 1
{'model_name': 'Yolo', 'model_config': 'data/task_configs/yolo/street_5/yolo_model.json', 'log_filename': 'yolo/street_5/FL_client_1_log', 'train': 'data/street_5/1/train.txt', 'test': 'data/street_5/1/test.txt', 'names': 'data/street_5/classes.names', 'n_cpu': 4, 'local_epoch': 5, 'batch_size': 1}
INFO:client:{'model_name': 'Yolo', 'model_config': 'data/task_configs/yolo/street_5/yolo_model.json', 'log_filename': 'yolo/street_5/FL_client_1_log', 'train': 'data/street_5/1/train.txt', 'test': 'data/street_5/1/test.txt', 'names': 'data/street_5/classes.names', 'n_cpu': 4, 'local_epoch': 5, 'batch_size': 1}
sent wakeup
on init
{'model_def': 'config/yolov3-custom-street.cfg', 'pretrained_weights': 'weights/darknet53.conv.74', 'multiscale_training': True, 'gradient_accumulations': 2, 'img_size': 416}
INFO:root:load data
train_size: 212
config/yolov3-custom-street.cfg
INFO:root:model construct completed
local model initialized done.
check client resource.
Ignore load average
update requested
INFO:client:### Round 0 ###
INFO:client:received initial model
yolo_model.pkl
load model from file
Traceback (most recent call last):
  File "fl_client.py", line 266, in <module>
    FederatedClient("127.0.0.1", opt.port, opt.config_file, opt.gpu, opt.ignore_load)
  File "fl_client.py", line 96, in __init__
    self.sio.wait()
  File "/home/imsdev1/fahad/Federated_object_detection/venv/lib/python3.8/site-packages/socketIO_client/__init__.py", line 251, in wait
    self._process_packets()
  File "/home/imsdev1/fahad/Federated_object_detection/venv/lib/python3.8/site-packages/socketIO_client/__init__.py", line 278, in _process_packets
    self._process_packet(engineIO_packet)
  File "/home/imsdev1/fahad/Federated_object_detection/venv/lib/python3.8/site-packages/socketIO_client/__init__.py", line 491, in _process_packet
    delegate(parse_socketIO_packet_data(socketIO_packet_data), namespace)
  File "/home/imsdev1/fahad/Federated_object_detection/venv/lib/python3.8/site-packages/socketIO_client/__init__.py", line 513, in _on_event
    namespace._find_packet_callback(event)(*args)
  File "fl_client.py", line 140, in on_request_update
    self.local_model.set_weights(weights)
  File "fl_client.py", line 42, in set_weights
    self.model.set_weights(new_weights)
  File "/home/imsdev1/fahad/Federated_object_detection/model/model_wrapper.py", line 80, in set_weights
    param_ = torch.from_numpy(parameters[i]).cuda()
  File "/home/imsdev1/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
disconnect

**Comment by fahnub** [comment]
Settings:
Ubuntu 20.04
Cuda 11.0
Nvidia Quadro P2000

**Comment by SHM1201** [comment]
Hi, I am facing the same error with the same traceback for my environment. Is there any solution to this? I have tried searching for this issue online but I couldn't find a relevant solution to it. In dire need of help.

**Comment by fahnub** [comment]
Unfortunately, I wasnt able to resolve it.
